ALTER TABLE users
    ADD COLUMN IF NOT EXISTS subscription_plan VARCHAR(50) NOT NULL DEFAULT 'FREE';

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS subscription_status VARCHAR(50) NOT NULL DEFAULT 'INACTIVE';

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS stripe_customer_id VARCHAR(255);

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS stripe_subscription_id VARCHAR(255);